In [3]:
import pandas as pd
import numpy as np

# Conditional Selection

In [5]:
df=pd.read_csv('ramen-ratings.csv')

In [6]:
df.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

To explore data , ask intersting questions

Explore ramen dishes served in Taiwan

In [10]:
df.loc[df['Country'] =='Taiwan'] # Select all rows when country == Taiwan

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
40,2540,Wei Lih,GGE Noodle Snack Wheat Crackers Mexican Spicy,Pack,Taiwan,3.25,NaN
65,2515,Uni-President,Man Han Feast Spicy Beef Flavor Instant Noodles,Bowl,Taiwan,5,NaN
68,2512,Mom's Dry Noodle,Dan Dan Noodle,Pack,Taiwan,5,NaN
...,...,...,...,...,...,...,...
2500,80,Unif / Tung-I,Artificial Chicken,Pack,Taiwan,3.5,NaN
2512,68,Wei Lih,Jah Jan Mien Instant Noodle With Fried Soybean...,Pack,Taiwan,4,NaN
2522,58,Ve Wong,A-One Bun Tom Shrimp,Pack,Taiwan,3,NaN
2537,43,Kim Ve Wong,Jaopai Series: Vegetarian Instant Noodles,Bowl,Taiwan,0,NaN
2572,8,Tung-I,Chinese Beef Instant Rice Noodle,Pack,Taiwan,3,NaN

Have a look at the raman dishes which have rating above than average

In [15]:
# When trying to get the stars more than 2.5 as avg this give an error as data 
# the stars column is str not float as there are some values 'unrates'

In [19]:
df=df.loc[df.Stars != 'Unrated'] # to delete all rows which stars value==unrated

In [23]:
df.Stars.astype(float) # change type of data to float

0       3.75
1       1.00
2       2.25
3       2.75
4       3.75
        ...
2575    3.50
2576    1.00
2577    2.00
2578    2.00
2579    0.50
Name: Stars, Length: 2577, dtype: float64

In [24]:
df.Stars

0       3.75
1       1.00
2       2.25
3       2.75
4       3.75
        ...
2575    3.50
2576    1.00
2577    2.00
2578    2.00
2579    0.50
Name: Stars, Length: 2577, dtype: float64

In [27]:
df.loc[df.Stars > 2.5]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
5,2575,Samyang Foods,Kimchi song Song Ramen,Pack,South Korea,4.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4.00,NaN
...,...,...,...,...,...,...,...
2564,16,Samyang,Kalgug-Su (Spicy),Pack,South Korea,3.50,NaN
2566,14,Samyang,Hot,Pack,South Korea,3.50,NaN
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4
2572,8,Tung-I,Chinese Beef Instant Rice Noodle,Pack,Taiwan,3.00,NaN
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.50,NaN

Served dishes in Taiwan with above average ratings

In [29]:
# & and  , | or , ~ not 
df.loc[(df['Country'] =='Taiwan') & (df['Stars'] > 2.5)]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
40,2540,Wei Lih,GGE Noodle Snack Wheat Crackers Mexican Spicy,Pack,Taiwan,3.25,NaN
65,2515,Uni-President,Man Han Feast Spicy Beef Flavor Instant Noodles,Bowl,Taiwan,5.00,NaN
68,2512,Mom's Dry Noodle,Dan Dan Noodle,Pack,Taiwan,5.00,NaN
79,2501,Happy Cook,Toona Paste Noodle,Pack,Taiwan,4.00,NaN
...,...,...,...,...,...,...,...
2499,81,Unif / Tung-I,Artificial Spicy Beef,Pack,Taiwan,3.50,NaN
2500,80,Unif / Tung-I,Artificial Chicken,Pack,Taiwan,3.50,NaN
2512,68,Wei Lih,Jah Jan Mien Instant Noodle With Fried Soybean...,Pack,Taiwan,4.00,NaN
2522,58,Ve Wong,A-One Bun Tom Shrimp,Pack,Taiwan,3.00,NaN
2572,8,Tung-I,Chinese Beef Instant Rice Noodle,Pack,Taiwan,3.00,NaN

In [31]:
df.loc[(df['Country'] =='Taiwan') & (df['Stars'] > 2.5) , ['Brand','Style']]

                 Brand Style
3              Wei Lih  Pack
40             Wei Lih  Pack
65       Uni-President  Bowl
68    Mom's Dry Noodle  Pack
79          Happy Cook  Pack
...                ...   ...
2499     Unif / Tung-I  Pack
2500     Unif / Tung-I  Pack
2512           Wei Lih  Pack
2522           Ve Wong  Pack
2572            Tung-I  Pack

[191 rows x 2 columns]

Have a look at the dishes served in both Finland and sweden

In [34]:
df.loc[(df['Country']=='Finland') | (df['Country']=='Sweden')]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
675,1905,Pirkka,Nuudeli Kana Nudlar Kyckling,Pack,Finland,3.50,NaN
816,1764,Pirkka,Nuudeli Tom Yum Katkarapu,Pack,Finland,3.75,NaN
856,1724,Pirkka,Nuudeli Liha Nudlar Kott,Pack,Finland,3.50,NaN
1026,1554,ICA,Asia Fast Noodles Snabbnudlar RÃ¤ksmak,Pack,Sweden,3.00,NaN
1063,1517,Katoz,Instant Noodles Spicy Chili,Pack,Sweden,3.50,NaN
1093,1487,ICA,Asia Snabbnudlar Kycklingsmak,Pack,Sweden,3.25,NaN

In [35]:
df.loc[df.Country.isin(['Finland','Sweden'])]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
675,1905,Pirkka,Nuudeli Kana Nudlar Kyckling,Pack,Finland,3.50,NaN
816,1764,Pirkka,Nuudeli Tom Yum Katkarapu,Pack,Finland,3.75,NaN
856,1724,Pirkka,Nuudeli Liha Nudlar Kott,Pack,Finland,3.50,NaN
1026,1554,ICA,Asia Fast Noodles Snabbnudlar RÃ¤ksmak,Pack,Sweden,3.00,NaN
1063,1517,Katoz,Instant Noodles Spicy Chili,Pack,Sweden,3.50,NaN
1093,1487,ICA,Asia Snabbnudlar Kycklingsmak,Pack,Sweden,3.25,NaN

Get the Top Ten values that are not null

In [38]:
df.loc[~df['Top Ten'].isnull()]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5.00,2016 #10
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5.00,2016 #1
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5.00,2016 #8
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5.00,2016 #5
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5.00,2016 #9
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5.00,2016 #7
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5.00,2015 #10
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5.00,2015 #7
995,1585,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5.00,2015 #4
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5.00,2015 #9
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5.00,2015 #6
1080,1500,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5.00,2015 #1
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5.00,2013 #10
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5.00,2015 #8
1230,1350,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5.00,2014 #7
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5.00,2014 #4
1272,1308,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5.00,2014 #9
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5.00,2014 #10
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5.00,2014 #8
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5.00,2014 #5
1397,1183,Paldo,Cheese Noodle,Pack,South Korea,5.00,2014 #6
1493,1087,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5.00,2014 #1
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5.00,2013 #1
1589,991,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5.00,2013 #2
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5.00,2013 #4
1670,910,Paldo,Namja Ramyun,Bowl,South Korea,4.25,\n
1757,823,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5.00,2013 #9
1846,734,Indomie,Mi Goreng Rasa Ayam Panggang Jumbo (Local),Pack,Indonesia,5.00,\n
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5.00,2013 #3
1972,608,Koka,Spicy Black Pepper,Pack,Singapore,5.00,2012 #10
2002,578,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7
2146,434,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.50,2012 #5
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5.00,2012 #3
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6
2248,332,Nongshim,Champong Oriental Noodles,Cup,South Korea,3.75,\n
2295,285,Doll,Artificial Chicken,Pack,Hong Kong,4.50,2012 #9
2475,105,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5.00,2012 #1
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.00,2012 #2
2535,45,Indomie,Mi Goreng Sate,Pack,Indonesia,5.00,\n
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4.00,2013 #6
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4

In [39]:
df.loc[df['Top Ten'].notnull()]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5.00,2016 #10
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5.00,2016 #1
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5.00,2016 #8
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5.00,2016 #5
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5.00,2016 #9
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5.00,2016 #7
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5.00,2015 #10
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5.00,2015 #7
995,1585,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5.00,2015 #4
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5.00,2015 #9
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5.00,2015 #6
1080,1500,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5.00,2015 #1
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5.00,2013 #10
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5.00,2015 #8
1230,1350,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5.00,2014 #7
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5.00,2014 #4
1272,1308,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5.00,2014 #9
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5.00,2014 #10
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5.00,2014 #8
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5.00,2014 #5
1397,1183,Paldo,Cheese Noodle,Pack,South Korea,5.00,2014 #6
1493,1087,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5.00,2014 #1
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5.00,2013 #1
1589,991,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5.00,2013 #2
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5.00,2013 #4
1670,910,Paldo,Namja Ramyun,Bowl,South Korea,4.25,\n
1757,823,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5.00,2013 #9
1846,734,Indomie,Mi Goreng Rasa Ayam Panggang Jumbo (Local),Pack,Indonesia,5.00,\n
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5.00,2013 #3
1972,608,Koka,Spicy Black Pepper,Pack,Singapore,5.00,2012 #10
2002,578,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7
2146,434,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.50,2012 #5
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5.00,2012 #3
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6
2248,332,Nongshim,Champong Oriental Noodles,Cup,South Korea,3.75,\n
2295,285,Doll,Artificial Chicken,Pack,Hong Kong,4.50,2012 #9
2475,105,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5.00,2012 #1
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.00,2012 #2
2535,45,Indomie,Mi Goreng Sate,Pack,Indonesia,5.00,\n
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4.00,2013 #6
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4

# Assigning Data

Assign values of specific column by specific values

In [52]:
df.loc['Brand']='Doll'
df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,isCup
0,2580.0,Doll,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN,1.0
1,2579.0,Doll,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.0,NaN,0.0
2,2578.0,Doll,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN,1.0
3,2577.0,Doll,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN,0.0
4,2576.0,Doll,Singapore Curry,Pack,India,3.75,NaN,0.0
...,...,...,...,...,...,...,...,...
2577,3.0,Doll,Tom Yum Shrimp,Pack,Thailand,2.0,NaN,0.0
2578,2.0,Doll,Tom Yum Chili Flavor,Pack,Thailand,2.0,NaN,0.0
2579,1.0,Doll,Miso Ramen,Pack,USA,0.5,NaN,0.0
isCup,NaN,False,NaN,NaN,NaN,NaN,NaN,False
Brand,Doll,Doll,Doll,Doll,Doll,Doll,Doll,Doll

Adding a new column to table

In [51]:
df.loc['isCup']=(df.Style=='Cup')
df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,isCup
0,2580.0,Doll,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN,1.0
1,2579.0,Doll,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.0,NaN,0.0
2,2578.0,Doll,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN,1.0
3,2577.0,Doll,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN,0.0
4,2576.0,Doll,Singapore Curry,Pack,India,3.75,NaN,0.0
...,...,...,...,...,...,...,...,...
2577,3.0,Doll,Tom Yum Shrimp,Pack,Thailand,2.0,NaN,0.0
2578,2.0,Doll,Tom Yum Chili Flavor,Pack,Thailand,2.0,NaN,0.0
2579,1.0,Doll,Miso Ramen,Pack,USA,0.5,NaN,0.0
isCup,NaN,False,NaN,NaN,NaN,NaN,NaN,False
Brand,Doll,Doll,Doll,Doll,Doll,Doll,Doll,Doll

Replce values of Review # column to 1 to len of data

In [55]:
len(df)

2579

In [60]:
df['Review #']=list(range(1,2580))  # note range (1 to len(df)+1)
df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,isCup
0,1,Doll,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN,1.0
1,2,Doll,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.0,NaN,0.0
2,3,Doll,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN,1.0
3,4,Doll,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN,0.0
4,5,Doll,Singapore Curry,Pack,India,3.75,NaN,0.0
...,...,...,...,...,...,...,...,...
2577,2575,Doll,Tom Yum Shrimp,Pack,Thailand,2.0,NaN,0.0
2578,2576,Doll,Tom Yum Chili Flavor,Pack,Thailand,2.0,NaN,0.0
2579,2577,Doll,Miso Ramen,Pack,USA,0.5,NaN,0.0
isCup,2578,False,NaN,NaN,NaN,NaN,NaN,False
Brand,2579,Doll,Doll,Doll,Doll,Doll,Doll,Doll